# Generated by Django 6.1 on 2026-08-10 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('trace', 'Trace'), ('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], db_index=True, default='info', max_length=16)),
                ('body', models.TextField()),
                ('logger', models.CharField(blank=True, db_index=True, max_length=200)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('span_id', models.CharField(blank=True, max_length=16)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64)),
                ('release', models.CharField(blank=True, max_length=128)),
                ('server_name', models.CharField(blank=True, max_length=256)),
                ('attributes', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', '-timestamp'], name='log_project_recent'), models.Index(fields=['trace_id', 'timestamp'], name='log_trace_order')],
            },
        ),
    ]
