# Generated by Django 6.1 on 2026-08-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_placeholder_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='platform',
        ),
    ]
