# Generated by Django 6.1 on 2026-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trace_sharing',
            field=models.BooleanField(default=False, help_text='Combine traces with other projects in this organization that also have it on.'),
        ),
    ]
