# Generated by Django 6.1 on 2026-08-10 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('span_id', models.CharField(max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('op', models.CharField(default='http.server', max_length=64)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('not_found', 'Not found'), ('unauthenticated', 'Unauthenticated'), ('invalid_argument', 'Invalid argument'), ('internal_error', 'Internal error'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='ok', max_length=32)),
                ('start_timestamp', models.DateTimeField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('duration_ms', models.FloatField(db_index=True)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64)),
                ('release', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('span_id', models.CharField(max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=16)),
                ('op', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='ok', max_length=32)),
                ('start_timestamp', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('duration_ms', models.FloatField(db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='tracing.transaction')),
            ],
            options={
                'ordering': ['start_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project', 'name', '-timestamp'], name='txn_project_name_recent'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project', '-timestamp'], name='txn_project_recent'),
        ),
        migrations.AddIndex(
            model_name='span',
            index=models.Index(fields=['transaction', 'start_timestamp'], name='span_txn_order'),
        ),
    ]
