# Generated by Django 6.1 on 2026-08-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='measurements',
            field=models.JSONField(default=dict),
        ),
    ]
