# Generated by Django 6.1 on 2026-08-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0002_issue_category_issue_evidence_issue_issue_type'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('new_issue', 'A new issue appears'), ('regression', 'A resolved issue happens again'), ('frequency', 'An issue crosses a rate')], default='new_issue', max_length=16)),
                ('threshold', models.PositiveIntegerField(default=10)),
                ('window_minutes', models.PositiveIntegerField(default=5)),
                ('level', models.CharField(blank=True, choices=[('fatal', 'Fatal'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('debug', 'Debug')], default='', max_length=16)),
                ('webhook_url', models.URLField(max_length=500)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('enabled', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=300)),
                ('delivery', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_fires', to='issues.issue')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fires', to='alerts.alertrule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['project', 'enabled'], name='alerts_aler_project_e5aae8_idx'),
        ),
        migrations.AddIndex(
            model_name='alertfire',
            index=models.Index(fields=['rule', 'issue', '-created_at'], name='alerts_aler_rule_id_4b4f46_idx'),
        ),
        migrations.AddIndex(
            model_name='alertfire',
            index=models.Index(fields=['-created_at'], name='alerts_aler_created_50e7da_idx'),
        ),
    ]
