# Generated by Django 6.1 on 2026-08-10 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('fatal', 'Fatal'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('debug', 'Debug')], db_index=True, default='error', max_length=16)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('exception_type', models.CharField(blank=True, max_length=256)),
                ('exception_value', models.TextField(blank=True)),
                ('culprit', models.CharField(blank=True, max_length=512)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64)),
                ('release', models.CharField(blank=True, db_index=True, max_length=128)),
                ('server_name', models.CharField(blank=True, max_length=256)),
                ('payload', models.JSONField()),
                ('tags', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', '-timestamp'], name='event_project_recent')],
            },
        ),
    ]
