# Generated by Django 6.1 on 2026-08-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('issues', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='issues.issue'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['issue', '-timestamp'], name='event_issue_recent'),
        ),
    ]
