# Generated by Django 6.1 on 2026-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_issue_event_event_issue_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='span_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
