# Generated by Django 6.1 on 2026-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_span_id_event_trace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flags',
            field=models.JSONField(default=dict),
        ),
    ]
