# Generated by Django 6.1 on 2026-08-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('fingerprint_components', models.JSONField(default=list)),
                ('title', models.CharField(max_length=512)),
                ('culprit', models.CharField(blank=True, max_length=512)),
                ('level', models.CharField(choices=[('fatal', 'Fatal'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('debug', 'Debug')], db_index=True, default='error', max_length=16)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='unresolved', max_length=16)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['project', 'status', '-last_seen'], name='issue_triage_order')],
                'constraints': [models.UniqueConstraint(fields=('project', 'fingerprint'), name='unique_issue_fingerprint_per_project')],
            },
        ),
    ]
