# Generated by Django 6.1 on 2026-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('error', 'Error'), ('performance', 'Performance')], db_index=True, default='error', max_length=16),
        ),
        migrations.AddField(
            model_name='issue',
            name='evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('n_plus_one_queries', 'N+1 Queries'), ('slow_db_query', 'Slow DB Query')], max_length=32),
        ),
    ]
