# Generated by Django 6.1 on 2026-08-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_category_issue_evidence_issue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='first_release',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
